import type { CartItem, Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Performance Running Jacket",
    slug: "performance-running-jacket",
    description: "Lightweight, water-resistant jacket perfect for running in all weather conditions.",
    fullDescription:
      "Our Performance Running Jacket is designed for serious runners who don't let weather get in their way. Featuring our proprietary WindBlock technology, this jacket keeps you protected from the elements while remaining breathable to prevent overheating. The reflective details ensure visibility in low-light conditions, and multiple pockets provide convenient storage for your essentials.",
    price: 89.99,
    originalPrice: 119.99,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "Running",
    rating: 4.8,
    reviewCount: 124,
    isNew: true,
    isFeatured: true,
    availableSizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Blue", hex: "#0000FF" },
      { name: "Red", hex: "#FF0000" },
    ],
    material: "88% Polyester, 12% Elastane",
  },
  {
    id: "2",
    name: "Pro Training Shorts",
    slug: "pro-training-shorts",
    description: "Breathable training shorts with moisture-wicking technology for intense workouts.",
    price: 34.99,
    originalPrice: 44.99,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "Training",
    rating: 4.5,
    reviewCount: 89,
    isFeatured: true,
    availableSizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Gray", hex: "#808080" },
      { name: "Navy", hex: "#000080" },
    ],
  },
  {
    id: "3",
    name: "Elite Basketball Shoes",
    slug: "elite-basketball-shoes",
    description: "High-performance basketball shoes with superior ankle support and cushioning.",
    price: 129.99,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "Basketball",
    rating: 4.9,
    reviewCount: 56,
    isNew: true,
    isFeatured: true,
    availableSizes: ["7", "8", "9", "10", "11", "12"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Red", hex: "#FF0000" },
    ],
  },
  {
    id: "4",
    name: "Compression Long Sleeve",
    slug: "compression-long-sleeve",
    description: "Compression fit long sleeve shirt for enhanced performance and muscle support.",
    price: 49.99,
    originalPrice: 59.99,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: "Training",
    rating: 4.6,
    reviewCount: 78,
    isFeatured: true,
    availableSizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Blue", hex: "#0000FF" },
      { name: "White", hex: "#FFFFFF" },
    ],
  },
  {
    id: "5",
    name: "Soccer Cleats Pro",
    slug: "soccer-cleats-pro",
    description: "Professional-grade soccer cleats designed for speed and control on the field.",
    price: 119.99,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "Soccer",
    rating: 4.7,
    reviewCount: 42,
    isFeatured: true,
    availableSizes: ["7", "8", "9", "10", "11", "12"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Green", hex: "#008000" },
      { name: "Yellow", hex: "#FFFF00" },
    ],
  },
  {
    id: "6",
    name: "Performance Leggings",
    slug: "performance-leggings",
    description: "High-waisted performance leggings with pocket, perfect for yoga and running.",
    price: 59.99,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: "Women",
    rating: 4.8,
    reviewCount: 112,
    isFeatured: true,
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Gray", hex: "#808080" },
      { name: "Purple", hex: "#800080" },
    ],
  },
  {
    id: "7",
    name: "Dri-Fit Training Tee",
    slug: "dri-fit-training-tee",
    description: "Lightweight, sweat-wicking fabric keeps you dry during workouts.",
    price: 29.99,
    originalPrice: 34.99,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: "Men",
    rating: 4.5,
    reviewCount: 87,
    isFeatured: true,
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Blue", hex: "#0000FF" },
      { name: "Red", hex: "#FF0000" },
    ],
  },
  {
    id: "8",
    name: "Ultralight Running Shoes",
    slug: "ultralight-running-shoes",
    description: "Featherlight running shoes with responsive cushioning for long-distance comfort.",
    price: 149.99,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "Running",
    rating: 4.9,
    reviewCount: 64,
    isNew: true,
    isFeatured: true,
    availableSizes: ["7", "8", "9", "10", "11", "12"],
    colors: [
      { name: "Gray", hex: "#808080" },
      { name: "Blue", hex: "#0000FF" },
      { name: "Orange", hex: "#FFA500" },
    ],
  },
]

export const mockCartItems: CartItem[] = [
  {
    id: "1",
    name: "Performance Running Jacket",
    price: 89.99,
    quantity: 1,
    size: "M",
    color: "Black",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "2",
    name: "Pro Training Shorts",
    price: 34.99,
    quantity: 2,
    size: "L",
    color: "Gray",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "4",
    name: "Compression Long Sleeve",
    price: 49.99,
    quantity: 1,
    size: "XL",
    color: "Blue",
    image: "/placeholder.svg?height=600&width=600",
  },
]

export const mockCategories = [
  {
    id: "1",
    name: "Men",
    slug: "men",
    description: "Men's sportswear for all activities",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "2",
    name: "Women",
    slug: "women",
    description: "Women's sportswear for all activities",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "3",
    name: "Running",
    slug: "running",
    description: "Gear for runners of all levels",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "4",
    name: "Training",
    slug: "training",
    description: "Equipment for gym and home workouts",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "5",
    name: "Basketball",
    slug: "basketball",
    description: "Basketball shoes and apparel",
    image: "/placeholder.svg?height=600&width=600",
  },
  {
    id: "6",
    name: "Soccer",
    slug: "soccer",
    description: "Soccer cleats and equipment",
    image: "/placeholder.svg?height=600&width=600",
  },
]

